version: "3"
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          # Uncomment this when using postgres.
    networks:
      - fullstack
  fullstack-postgres:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    networks:
      - fullstack
volumes:
  my_dbdata:
  api:

networks:
  fullstack:
    driver: bridge
