version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.1
    working_directory: ~/hello-world
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod download
      - run: go build
      - run: go test -v ./...
